### ISSUE TITLE
Sharding across multiple machines

### ISSUE THREAD

**Issue by iquerame2** [tigergraph/pyTigerGraph#26]
I am trying to deploy sharding in a multi-machine setting, where each physical machine (VM) contains a different shard collection (potentially with replicas). In particular, is it possible not to have the same shard collection automatically replicated across all machines? Otherwise said, can we work with different database fragments on each machine?
Please tell me if you know some DBMS that ensure this setting.
Thank you!

**Comment by elliotmartinTG** [comment]
TigerGraph handles data shard and replication automatically. There is no way for the user to do this. The same is true for querying, there is no way to query data in a specific shard as TigerGraph automatically manages this for the user so that they do not need to worry about this and can just focus on writing queries for the data. 

You are able to specify the number of replicas and partitions for the cluster during install time. More information is available here:
https://docs.tigergraph.com/tigergraph-server/current/ha/ha-cluster
